/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Dell
 */
public class Home extends javax.swing.JFrame {

    private boolean True;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Student Result Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Admin_button = new javax.swing.JButton();
        Student_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/School-Exterior-and-Entrance.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-admin-settings-male-30.png"))); // NOI18N
        Admin_button.setText("Admin");
        Admin_button.setMaximumSize(new java.awt.Dimension(100, 30));
        Admin_button.setMinimumSize(new java.awt.Dimension(100, 30));
        Admin_button.setPreferredSize(new java.awt.Dimension(100, 30));
        Admin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 150, 40));

        Student_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Student_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-schoolboy-at-a-desk-30.png"))); // NOI18N
        Student_button.setText("Student");
        Student_button.setMaximumSize(new java.awt.Dimension(10, 10));
        Student_button.setMinimumSize(new java.awt.Dimension(10, 10));
        Student_button.setPreferredSize(new java.awt.Dimension(100, 30));
        Student_button.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Student_buttonComponentAdded(evt);
            }
        });
        Student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Student_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 200));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 200));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 200));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-810, -520, 1510, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_buttonActionPerformed
        setVisible(false);
        Student frame=new Student();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setTitle("Student Login Form");
        
    }//GEN-LAST:event_Student_buttonActionPerformed

    private void Admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_buttonActionPerformed
        setVisible(false);
        AdminLogin frame=new AdminLogin();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setTitle("Admin Login Form");
    }//GEN-LAST:event_Admin_buttonActionPerformed

    private void Student_buttonComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Student_buttonComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Student_buttonComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_button;
    private javax.swing.JButton Student_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
