/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectionProviderCode;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;



/**
 *
 * @author Dell
 */
public class InsertStudent extends javax.swing.JFrame {

    /**
     * Creates new form InsertStudent
     */
    public InsertStudent() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Insert Student Details");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        name_textfield = new javax.swing.JTextField();
        rollNo_textfield = new javax.swing.JTextField();
        gender_ComboBox = new javax.swing.JComboBox<>();
        fatherName_textfield = new javax.swing.JTextField();
        course_ComboBox = new javax.swing.JComboBox<>();
        branch_ComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Roll No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Father's Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Course");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Branch");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubmitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-submit-document-32.png"))); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/backButton3.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, 40));
        getContentPane().add(name_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 37, 120, -1));
        getContentPane().add(rollNo_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 86, 120, -1));

        gender_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(gender_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 110, -1));
        getContentPane().add(fatherName_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 110, -1));

        course_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        course_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTech", "MTech" }));
        getContentPane().add(course_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, -1));

        branch_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        branch_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "Civil", "Mechanical", "Electronics" }));
        getContentPane().add(branch_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic2.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(700, 600));
        jLabel7.setMinimumSize(new java.awt.Dimension(700, 600));
        jLabel7.setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, 630, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_ComboBoxActionPerformed
        
        
    }//GEN-LAST:event_gender_ComboBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String name = name_textfield.getText();
        String rollNo = rollNo_textfield.getText();
        String gender = (String)gender_ComboBox.getSelectedItem();
        String fatherName=fatherName_textfield.getText();
        String course=(String)course_ComboBox.getSelectedItem();
        String branch=(String)branch_ComboBox.getSelectedItem();
        
        
        try{
            Connection con =ConnectionProviderCode.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into student values('"+ name + "', '" + rollNo +"', '"+ gender +"', '"+ fatherName +"', '"+ course +"', '"+ branch +"');");

            JOptionPane.showMessageDialog(null, "Insertion Successful");
            setVisible(false);
            InsertStudent frame=new InsertStudent();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
            frame.setTitle("Insert Student Details");
           
        }
        catch(Exception excp){
            JOptionPane.showMessageDialog(null, excp.toString());
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        int response=JOptionPane.showConfirmDialog(null, "Want to go back?","Back",JOptionPane.YES_NO_OPTION);
        
        if(response==0)
        {
            setVisible(false);
            Admin frame=new Admin();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }      
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> branch_ComboBox;
    private javax.swing.JComboBox<String> course_ComboBox;
    private javax.swing.JTextField fatherName_textfield;
    private javax.swing.JComboBox<String> gender_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JTextField rollNo_textfield;
    // End of variables declaration//GEN-END:variables
}
